# Generated by Django 3.2.9 on 2021-11-24 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recharge.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0004_alter_retailer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='mobile_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000), recharge.models.validate_dmobile]),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='mobile_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000), recharge.models.validate_pdmobile]),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='mobile_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000), recharge.models.validate_rmobile]),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcbuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
