# Generated by Django 3.2.9 on 2021-11-24 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0005_auto_20211124_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarydistributor',
            name='airtel_small_percentage',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
