# Generated by Django 3.2.9 on 2021-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0006_alter_primarydistributor_airtel_small_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='decf10a', max_length=7),
        ),
        migrations.AddField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='0ff32045', max_length=7),
        ),
    ]
