# Generated by Django 3.2.9 on 2021-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0007_auto_20211124_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='retailer_referral_code',
            field=models.CharField(default='896db48b', max_length=8),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='f67802d', max_length=7),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='cf8cca70', max_length=8),
        ),
    ]
