# Generated by Django 3.2.9 on 2021-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0010_auto_20211124_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='retailer_referral_code',
            field=models.CharField(default='751c5f34', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='e3c0b2c', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='5ef4cf8f', max_length=8, unique=True),
        ),
    ]
