# Generated by Django 3.2.9 on 2021-11-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recharge.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0003_auto_20211124_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL, validators=[recharge.models.validate_retailer]),
        ),
    ]
