# Generated by Django 3.2.9 on 2021-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0014_auto_20211124_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='retailer_referral_code',
            field=models.CharField(default='dadc9f8a', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='a58c91c', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='62ab67bd', max_length=8, unique=True),
        ),
    ]
