# Generated by Django 3.2.9 on 2021-11-27 14:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0016_auto_20211125_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('Airtel', 'Airtel'), ('Jio', 'Jio'), ('VI', 'VI'), ('BSNL', 'BSNL')], max_length=255)),
                ('plan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('telecom_area', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Kolkata', 'Kolkata'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Mumbai Metro', 'Mumbai Metro'), ('Northeast', 'Northeast'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Tamilnadu', 'Tamilnadu'), ('Uttar Pradesh East', 'Uttar Pradesh East'), ('Uttar Pradesh West', 'Uttar Pradesh West'), ('West Bengal', 'West Bengal')], max_length=255)),
                ('details', models.TextField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='distributor',
            name='retailer_referral_code',
            field=models.CharField(default='9811a203', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='02b2668', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='e791f287', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_plan', to='recharge.rechargeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharging_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
