# Generated by Django 3.2.9 on 2021-11-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0019_auto_20211129_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='coupon_code',
            field=models.CharField(default='d5cfd4aecd', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='retailer_referral_code',
            field=models.CharField(default='439820cc', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='distributor_referral_code',
            field=models.CharField(default='92525c6', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='primarydistributor',
            name='retailer_referral_code',
            field=models.CharField(default='a32713c0', max_length=8, unique=True),
        ),
    ]
